on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      run-manually:
        description: 'RUN_WORKFLOW_MANUALLY'
        required: true
        type: boolean
name: train-deploy
jobs:
  train:
    name: train new model
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout branch
      uses: actions/checkout@v2
      with:
        path: master
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
    - 
      name: Build Docker Train
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.train
        load: true
        push: false
        tags: train-image:latest
        build-args: |
          GOOGLE_SERVICE_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }}
    - 
      name: Run Docker Train
      uses: tj-actions/docker-run@v2
      with:
        image: train-image:latest
        name: train-image
  deploy:
    name: deploy new model
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout branch
      uses: actions/checkout@v2
      with:
        path: master
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
    - 
      name: Build Docker Train
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile.backend
        load: true
        push: false
        tags: deploy-image:latest
        build-args: |
          GOOGLE_SERVICE_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }}
    - 
      name: Run Docker Train
      uses: tj-actions/docker-run@v2
      with:
        image: deploy-image:latest
        name: deploy-image
