on: 
  push:
    branches:
      - test-github-actions
    workflow_dispatch:
    inputs:
      run-manually:
        description: 'RUN_WORKFLOW_MANUALLY'
        required: true
        type: boolean
name: train-deploy
jobs:
  train:
    name: train new model
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout branch
      uses: actions/checkout@v2
      with:
        path: test-github-actions
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile.train --tag train-image:{{ github.sha }}
    -
      name: Run Docker image
      run: |
        docker run \
          -v $(realpath models):/usr/src/models \
          train-image:{{ github.sha }}
