on: 
  push:
    branches:
      - test-github-actions
    workflow_dispatch:
    inputs:
      run-manually:
        description: 'RUN_WORKFLOW_MANUALLY'
        required: true
        type: boolean
name: train-deploy
jobs:
  train:
    name: train new model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: test-github-actions
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        dockerfile: Dockerfile.train
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
